{% set version="1.0.0" %}
{% set revision="d5db818f817f248d5bff8ca32b5d131054ff9edb" %}

package:
  name: uvaia 
  version: {{ version }}

source:
  git_url: https://github.com/quadram-institute-bioscience/uvaia.git
  git_rev: {{ revision }}
  md5: unused

build:
  number: 0
  skip: true # [osx]

requirements:
  build:
    - {{ compiler('c') }}
    - automake
    - libtool
    - pkg-config
    - make
    - check
    - zlib
    - xz
    - bzip2
  host:
    - check
    - zlib
    - xz
    - bzip2
  run:
    - zlib
    - xz
    - bzip2

test:
  commands:
    - uvaia -h 

about:
  home: https://github.com/quadram-institute-bioscience/uvaia
  license: 'GPLv3'
  license_file: LICENSE 
  summary: 'Reference-based alignment and sequence database search'

extra:
  identifiers:
    - biotools:uvaia
  skip-lints:
    - uses_git_url
    - uses_vcs_url
